version: "3"
services:
  words-db:
    image: mongo:latest
    volumes:
      - ./mongo-configs/init_db.js:/docker-entrypoint-initdb.d/init_db.js
    environment:
      - MONGO_INITDB_DATABASE=words
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - eesti

  eesti-backend:
    build: ./eesti-helper
    image: eesti-backend:${BACKEND_TAG}
    environment:
      - MONGO_HOST=words-db
      - MONGO_PORT=27017
    ports:
      - 8081:3000
    networks:
      default:
        aliases:
          - eesti

  eesti-frontend:
    build: ./eesti-site
    image: eesti-frontend:${FRONTEND_TAG}
    ports:
      - 8080:80
    networks:
      default:
        aliases:
          - eesti


