version: "3"
services:
  wordsDb:
    image: mongo:latest
    volumes:
      - ./mongo-configs/init_db.js:/docker-entrypoint-initdb.d/init_db.js
    environment:
            #      - MONGO_INITDB_ROOT_USERNAME=mongo_admin
            #      - MONGO_INITDB_ROOT_PASSWORD=admin_passw0rd
      - MONGO_INITDB_DATABASE=words
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - eesti

